# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "moogle"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benjamin Yu"]
  s.date = "2012-05-06"
  s.description = "Notification pushing to 3rd parties"
  s.email = "benjaminlyu@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "NOTICE.txt",
    "README.md",
    "Rakefile",
    "fixtures/vcr_cassettes/push_blog_entry.yml",
    "fixtures/vcr_cassettes/push_webhook_ping.yml",
    "lib/moogle.rb",
    "lib/moogle/commands.rb",
    "lib/moogle/commands/create_link.rb",
    "lib/moogle/commands/create_target.rb",
    "lib/moogle/commands/destroy_link.rb",
    "lib/moogle/commands/destroy_target.rb",
    "lib/moogle/commands/find_targets.rb",
    "lib/moogle/commands/push_blog_entry.rb",
    "lib/moogle/commands/push_email.rb",
    "lib/moogle/commands/push_webhook_ping.rb",
    "lib/moogle/commands/update_target.rb",
    "lib/moogle/error.rb",
    "lib/moogle/handlers/accept_notification.rb",
    "lib/moogle/models.rb",
    "lib/moogle/models/blog_target.rb",
    "lib/moogle/models/email_target.rb",
    "lib/moogle/models/facebook_target.rb",
    "lib/moogle/models/link.rb",
    "lib/moogle/models/post_log.rb",
    "lib/moogle/models/target.rb",
    "lib/moogle/models/twitter_target.rb",
    "lib/moogle/models/webhook_target.rb",
    "lib/moogle/representers/link_representer.rb",
    "lib/moogle/representers/target_representer.rb",
    "lib/moogle/version.rb",
    "moogle.gemspec",
    "schemas/events/blog_entry_pushed.json",
    "schemas/events/email_pushed.json",
    "schemas/events/link_created.json",
    "schemas/events/link_destroyed.json",
    "schemas/events/target_created.json",
    "schemas/events/target_destroyed.json",
    "schemas/events/target_updated.json",
    "schemas/events/webhook_ping_pushed.json",
    "schemas/messages/notification.json",
    "schemas/requests/create_link.json",
    "schemas/requests/create_target.json",
    "schemas/requests/destroy_link.json",
    "schemas/requests/destroy_target.json",
    "schemas/requests/find_targets.json",
    "schemas/requests/push_blog_entry.json",
    "schemas/requests/push_email.json",
    "schemas/requests/push_webhook_ping.json",
    "schemas/requests/update_target.json",
    "spec/commands/find_targets_spec.rb",
    "spec/commands/links_spec.rb",
    "spec/commands/push_blog_entry_spec.rb",
    "spec/commands/push_email_spec.rb",
    "spec/commands/push_webhook_ping_spec.rb",
    "spec/commands/targets_spec.rb",
    "spec/handlers/accept_notification_spec.rb",
    "spec/moogle_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/dependencies.rb",
    "spec/support/vcr.rb"
  ]
  s.homepage = "http://github.com/byu/moogle"
  s.licenses = ["Apache 2.0"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Notification pushing to 3rd parties"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 2.2.7"])
      s.add_runtime_dependency(%q<data_mapper>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<mail>, [">= 2.4.3"])
      s.add_runtime_dependency(%q<faraday>, [">= 0.7.6"])
      s.add_runtime_dependency(%q<rafaday>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<roar>, [">= 0.9.2"])
      s.add_runtime_dependency(%q<serf>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<uuidtools>, [">= 2.1.2"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<vcr>, ["~> 2.0.0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.8.1"])
      s.add_development_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_development_dependency(%q<dm-mysql-adapter>, [">= 0"])
    else
      s.add_dependency(%q<addressable>, [">= 2.2.7"])
      s.add_dependency(%q<data_mapper>, [">= 1.2.0"])
      s.add_dependency(%q<mail>, [">= 2.4.3"])
      s.add_dependency(%q<faraday>, [">= 0.7.6"])
      s.add_dependency(%q<rafaday>, [">= 0.1.0"])
      s.add_dependency(%q<roar>, [">= 0.9.2"])
      s.add_dependency(%q<serf>, [">= 0.9.0"])
      s.add_dependency(%q<uuidtools>, [">= 2.1.2"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<vcr>, ["~> 2.0.0"])
      s.add_dependency(%q<webmock>, ["~> 1.8.1"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_dependency(%q<dm-mysql-adapter>, [">= 0"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 2.2.7"])
    s.add_dependency(%q<data_mapper>, [">= 1.2.0"])
    s.add_dependency(%q<mail>, [">= 2.4.3"])
    s.add_dependency(%q<faraday>, [">= 0.7.6"])
    s.add_dependency(%q<rafaday>, [">= 0.1.0"])
    s.add_dependency(%q<roar>, [">= 0.9.2"])
    s.add_dependency(%q<serf>, [">= 0.9.0"])
    s.add_dependency(%q<uuidtools>, [">= 2.1.2"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<yard>, ["~> 0.7.5"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<vcr>, ["~> 2.0.0"])
    s.add_dependency(%q<webmock>, ["~> 1.8.1"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
    s.add_dependency(%q<dm-mysql-adapter>, [">= 0"])
  end
end

