require 'moogle/commands/create_link'
require 'moogle/commands/create_target'
require 'moogle/commands/destroy_link'
require 'moogle/commands/destroy_target'
require 'moogle/commands/find_targets'
require 'moogle/commands/update_target'
